# Analyzing Olympics Data with SQL and Python

Welcome to your webinar workspace! Here, you can follow along as we load data from multiple sources and then answer some questions about the Olympics!

## üèÉ&nbsp;&nbsp;Load in the Olympics Data
The primary data is available in your directory in the path `athlete_events.csv`.

The cell handles imports of the required packages and data.

In [ ]:
# Import libraries


# Import the data


# Preview the DataFrame

We can inspect the data types and the number of non-null rows per column using the [`.info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html) method.

In [ ]:
# Inspect the DataFrame

An easier way to inspect the number of missing values per column is to use [`.isna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) combined with [`.sum()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html).

In [ ]:
# Check missing values

The missing values in the `medal` column are because the dataset contains all competitors (not just those who won a medal). The remaining columns with missing values are not of interest to us today.

When exploring it, it looked as though some of the teams had hyphens and backslashes. Let's inspect it more closely by inspecting the unique values of the column. 

By using [`.value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) combined with [`.to_frame()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.to_frame.html), we can inspect the unique team names by frequency inside the interactive table viewer.

In [ ]:
# Inspect the team column

The `team` column is messy and sometimes contains countries separated by forward slashes or hyphens. Let's clean this by using [`.str.extract()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.extract.html) to extract the first country mentioned in the cases of slashes or hyphens (e.g., "Denmark/Sweden" becomes "Denmark").

If you want to learn more about regular expressions in Python, check out our [course](https://app.datacamp.com/learn/courses/regular-expressions-in-python) on the subject!

In [ ]:
# Split the team column on forward slashes and hyphens


# Preview the new column

## üåé&nbsp;&nbsp;Bring in additional data
Let's query a MariaDB database containing information on world nations to provide some additional data. 

We will store our query result as a pandas DataFrame named `nations_data`.

We now have country data that we can join with the Olympics data! We will use the [`.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html) method to combine the two DataFrames using the country and year columns.

A "left" join matches on rows in the olympics_data DataFrame, as some teams will not be present in the `countries_data` DataFrame.

In [ ]:
# Perform a left join between the two DataFrames


# Preview our data

## üèÜ&nbsp;&nbsp;Which countries have the most gold medals?
Let's start by calculating and visualizing the number of gold medals won by athletes from different countries. To do this, we can use the [`.query()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html) method to filter for rows where the `medal` is "Gold" and then use [.group_by()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) to aggregate by our `team_clean` variable. We then use [`.count()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html) to count the number of rows per team.

A second line sorts the values of our query so that we see the top teams first!

In [ ]:
# Count the number of gold medals earned by a country


# Sort the values


# Preview our count

We can visualize this using Plotly. Let's create a [choropleth map](https://plotly.com/python/choropleth-maps/) (i.e., a world map), where the country's color is based upon the medal count!

In [ ]:
# Create choropleth map of gold medal counts

## üìà&nbsp;&nbsp;How has the number of sports grown over time?
Another question we can ask ourselves is whether the number of individual sports has increased over time.

We will do this by grouping by the year and season (i.e., summer or winter) and then counting the number of unique using [.nunique()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html).

In [ ]:
# Group by year and season and count the number of unique values


# Preview the DataFrame

Let's plot this data using a [line plot](https://plotly.com/python/line-charts/), broken up by season!

In [ ]:
# Create a line plot for Summer and Winter Olympics

## üë™&nbsp;&nbsp;Bonus: Which countries had the highest medal count per 100'000 people in 2016?
Finally, let's use the population data we took from our SQL database! One exciting way will be to reproduce a variant of [this chart](https://www.businessinsider.com/2016-rio-olympics-medals-per-capita-2016-8?r=US&IR=T) from Business Insider of the number of medals per capita.

To account for team data, we will first aggregate by the team and event and select the [`.first()`](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.GroupBy.first.html) medal. This will allow us to get the medals by country and event.

In [ ]:
# Calculate event medals




# Preview the DataFrame

With the event data, we can perform a similar aggregation as before and calculate the ratio of medal count to population (divided by 10 million for interpretability).

In [ ]:
# Group by the team and population


# Calculate the number of medals per 10000000 people


# Sort values and take the top 20 countries


# Preview the DataFrame

We can now use a [bar chart](https://plotly.com/python/bar-charts/) to visualize the top countries by medals per capita!

In [ ]:
# Create a column chart by medal per capita

## Wrapping up
Congratulations! We successfully loaded data from two different sources, performed light cleaning, and then used the data to answer three questions with interactive charts.